### PR TITLE
Etasu status patient portal

### PR DESCRIPTION
**Pull request by KeeyanGhoreshi**
adds patient portal etasu status, as well as rebasing onto dev and making the etasu component usable in both the patient portal and main view

### CODE REVIEW

**Comment by plarocque4** [comment]
The diff has all of the VITE stuff too which makes it very hard to review.

**Comment by KeeyanGhoreshi** [comment]
that's because this branch is based off #112 and also rebased onto `dev`.  The diff looks like that because #112 is missing the commits from dev, and instead added a merge commit, so now we're out of sync.  I would recommend we close #112 and just use this PR since they contain the same changes and then point this one at `dev`

**Comment by avirgulto** [comment]
I'm getting the 404 error when trying to login to the patient portal again, because of the /auth/ in the url for the authentication. This was resolved for me before, not sure what changed or what I should do to resolve it. Removing the 'auth' part of the url works for authentication

**Comment by avirgulto** [comment]
Also not sure where the etasu status is in the patient portal? I went through each tab and don't see the section for it?

**Comment by KeeyanGhoreshi** [comment]
Oh right, I forgot to push up the supporting branch for rems admin

https://github.com/mcode/rems-admin/pull/138

Use this branch on rems admin and it should work

**Review by avirgulto — APPROVED** [review]
Looks good

**Pull request merged**
