### PR TITLE
add smart launch

### PR DESCRIPTION
**Pull request by KeeyanGhoreshi**
## Describe your changes

Makes the request generator a SMART app.  When launching through a launcher or sandbox, use `/launch`, otherwise accessing the page will initiate a standalone launch against whatever EHR is in the env variables.  You can use the reconnect button to connect to a different EHR by changing the setting after loading.

### CODE REVIEW

**Comment by rdingwell** [comment]
@KeeyanGhoreshi  when I try to run this I am getting errors related to setClient not being defined in App.js

 <Route exact path='/index' element={<Index callback = {setClient}/>} />

**Comment by plarocque4** [comment]
Works great to connect to the test-ehr but I ran into problems connecting to the moonshot-dev FHIR server. I put the url into the settings box for the base server and EHR server and selected "Reconnect EHR". This gave the login for the moonshot-dev server and the page loaded. I then tried to select a patient and although Jon Snow was there, there were no MedicationRequests available to select. I then looked back at the settings and it looks like the base server and her server reverted to the default localhost value.

**Comment by KeeyanGhoreshi** [comment]
Settings should update now.  Also the retrieval of requests is slow, not really anything I can do about that.  You can check the network tab to see them trickling in.  The loading of the requests is a bit confusing however.  There's no indication it's loading, and the dropdown updates from present, to not present, to present again when it's filled.  We can make a ticket for adding some loading indication.

**Comment by plarocque4** [comment]
When the connection times out and you try to query for a patient you get the following error:
```Unable to refresh. No offline_access or online_access scope found.```

Could the timeout be detected and indicated to the user so it is clear that a reconnection is necessary?

**Comment by plarocque4** [comment]
Settings update properly when launched from the moonshot. Now when I try to connect to the server specified (when originally connected to test-ehr) I get a failure:
```
smart.js:470 Uncaught (in promise) Error: bad_audience: Bad audience value
    at completeAuth (smart.js:470:1)
    at Object.ready (smart.js:640:1)
    at Object.ready (BrowserAdapter.js:151:1)
    at Index.jsx:10:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)
completeAuth @ smart.js:470
ready @ smart.js:640
ready @ BrowserAdapter.js:151
(anonymous) @ Index.jsx:10
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
Promise.then (async)
(anonymous) @ Index.jsx:10
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
webpackHotDevClient.js:138 src/components/Dashboard/DashboardElement.jsx
  Line 3:10:  'headers' is defined but never used  no-unused-vars

src/components/DisplayBox/DisplayBox.js
  Line 2:8:     'FHIR' is defined but never used                    no-unused-vars
  Line 12:7:    'propTypes' is assigned a value but never used      no-unused-vars
  Line 165:13:  'e' is defined but never used                       no-unused-vars
  Line 277:11:  'summaryColors' is assigned a value but never used  no-unused-vars
  Line 403:45:  'id' is defined but never used                      no-unused-vars

src/components/Inputs/CheckBox.js
  Line 9:17:  '_event' is defined but never used  no-unused-vars

src/components/RequestBox/RequestBox.js
  Line 2:8:     'FHIR' is defined but never used             no-unused-vars
  Line 63:23:   Unexpected empty method 'componentDidMount'  no-empty-function
  Line 352:14:  'e' is defined but never used                no-unused-vars
  Line 412:12:  'e' is defined but never used                no-unused-vars

src/components/SMARTBox/PatientBox.js
  Line 3:8:     'FHIR' is defined but never used                no-unused-vars
  Line 11:18:   'SelectChangeEvent' is defined but never used   no-unused-vars
  Line 165:13:  'results' is defined but never used             no-unused-vars
  Line 374:7:   'noResults' is assigned a value but never used  no-unused-vars

src/components/SettingsBox/SettingsBox.js
  Line 10:3:    '_event' is defined but never used           no-unused-vars
  Line 47:3:    '_event' is defined but never used           no-unused-vars
  Line 70:3:    '_event' is defined but never used           no-unused-vars
  Line 113:23:  Unexpected empty method 'componentDidMount'  no-empty-function

src/containers/Index.jsx
  Line 3:8:   'env' is defined but never used    no-unused-vars
  Line 6:15:  'props' is defined but never used  no-unused-vars

src/containers/Launch.jsx
  Line 1:23:  'useState' is defined but never used  no-unused-vars

src/containers/RequestBuilder.js
  Line 11:21:  'login' is defined but never used  no-unused-vars

src/util/auth.js
  Line 97:11:  'response' is defined but never used  no-unused-vars

src/util/fhir.js
  Line 1:42:  'auth' is defined but never used  no-unused-vars
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210
VM2825:2 Uncaught ReferenceError: process is not defined
    at 4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at 8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at 8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at e.onload (index.js:1:1)
```

**Comment by KeeyanGhoreshi** [comment]
token expiry should be getting handled by the client, it's meant to refresh when the token expires.  I added the missing `offline_access` scope, which will allow it to refresh its token.  The corresponding change must be made in Keycloak for the test-ehr.  Users that log in to the request generator should be given the `offline_access` role, which will allow them to refresh their client.

Outside of that, I made the error more clear by indicating that a refresh might resolve the issue, in case token refresh isn't working on some other server.

**Comment by KeeyanGhoreshi** [comment]
Also I can't seem to replicate the error you're having.  I connect to the test-ehr initially, then switch the base and ehr url in the settings to the moonshot server, and then hit the reconnect ehr button, and it works fine.

**Review by plarocque4 — DISMISSED** [review]
Looks good

**Review by plarocque4 — APPROVED** [review]

**Pull request merged**
